/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoetcp.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author iqbal
 */
public class BoardView extends javax.swing.JFrame {
    
    //aliases for view
    private final int PANEL_WIDTH = 300;
    private final int PANEL_HEIGHT = 300;
    private final int APP_WIDTH  = 340; 
    private final int APP_HEIGHT = 430;
    private final Color BG_BUTTON_COLOR = Color.GRAY;
    //end of aliases for view
    
    //object on the view
    private JButton squareButton[][] = new JButton[3][3];
    //end of object on the view

    //getter
    public JButton[][] getSquareButton() { return squareButton; }
    //end of getter
 
    //myfunction
    public void addButtontoPanel(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                squareButton[i][j] = new JButton();
                squareButton[i][j].setBackground(BG_BUTTON_COLOR);
                squareButton[i][j].setFont(new Font("Arial", Font.BOLD, 25));
                boardPanel.add(squareButton[i][j]);
            }
        }
    }
    
    public void customInit(){
        boardPanel.setSize(PANEL_WIDTH, PANEL_HEIGHT);
        this.setSize(APP_WIDTH, APP_HEIGHT);
    }
    
    public void updateGameBoard(char[][] gameBoard){
        for( int i = 0; i < 3; i++ ) {
            for( int j = 0; j < 3; j++ ) {
                squareButton[i][j].setText( String.valueOf( gameBoard[i][j] ) );
            }
        }
    }
    
    public void customMessageConditionLabel(String input){
       conditionLabel.setText(input);
    }
    
    public void setCustomPlayerLabel(String input){
        playerLabel.setText(input);
    }
    
    public void showCustomDialogBox(String inputString){
        JOptionPane.showMessageDialog(null, inputString);
    }
    
    public void disableClientButton(){
        clientBtn.setEnabled(false);
    }
    public void disableServerButton(){
        serverBtn.setEnabled(false);
    }
    //end of myfunction
    
    //event listener function
    public void addServerButonListener(ActionListener al){
        serverBtn.addActionListener(al);
    }
    public void addClientButonListener(ActionListener al){
        clientBtn.addActionListener(al);
    }
    public void addResetButonListener(ActionListener al){
        resetBtn.addActionListener(al);
    }
    public void addSquareButonListener(ActionListener al){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                squareButton[i][j].addActionListener(al);
            }
        }
    }
    //end of event listener function
    
    /**
     * Creates new form BoardView
     */
    public BoardView() {
        initComponents();
        addButtontoPanel();
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPanel = new javax.swing.JPanel();
        serverBtn = new javax.swing.JButton();
        clientBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        playerLabel = new javax.swing.JLabel();
        conditionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boardPanel.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        serverBtn.setText("Server");

        clientBtn.setText("Client");

        resetBtn.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conditionLabel))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverBtn)
                    .addComponent(resetBtn)
                    .addComponent(playerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientBtn)
                    .addComponent(conditionLabel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton clientBtn;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton serverBtn;
    // End of variables declaration//GEN-END:variables
}
